name: dagger-ci
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  dagger:
    name: dagger
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_OAUTH2_CLIENT_ID: ${{ secrets.TWITTER_OAUTH2_CLIENT_ID }}
      TWITTER_OAUTH2_CLIENT_SECRET: ${{ secrets.TWITTER_OAUTH2_CLIENT_SECRET }}
      INSTAGRAM_LONG_TERM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_LONG_TERM_ACCESS_TOKEN }}
      META_INSTAGRAM_APP_ID: ${{ secrets.META_INSTAGRAM_APP_ID }}
      OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagger-io
      # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dagger
        run: pip install dagger-io

      - name: Run dagger
        run: python3 ci/docker_hub.py

      # - name: Install Docker on EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_KEY }}
      #     script: |
      #       sudo apt-get update
      #       sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      #       echo \
      #         "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      #         $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #       sudo apt-get update
      #       sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      #       sudo docker --version

      # - name: Deploy to EC2 Instance
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_KEY }}
      #     script: |
      #       sudo echo ${{secrets.DOCKER_HUB_PASSWORD}} | sudo docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
      #       sudo docker stop stookers || true
      #       sudo docker rm stookers || true
      #       sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/poc:latest