name: dagger
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  dagger:
    name: dagger
    runs-on: ubuntu-latest
    env: 
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_OAUTH2_CLIENT_ID: ${{ secrets.TWITTER_OAUTH2_CLIENT_ID }}
      TWITTER_OAUTH2_CLIENT_SECRET: ${{ secrets.TWITTER_OAUTH2_CLIENT_SECRET }}
      TWITTER_WITH_IMAGE: ${{ vars.TWITTER_WITH_IMAGE }}
      INSTAGRAM_LONG_TERM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_LONG_TERM_ACCESS_TOKEN }}
      META_INSTAGRAM_APP_ID: ${{ secrets.META_INSTAGRAM_APP_ID }}
      AUTOGEN_MODEL: ${{ vars.AUTOGEN_MODEL }}
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagger-io
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install dagger
        run: pip install dagger-io
        env: 
          PIPPELI: 'pipeli'
      - name: Run dagger
        run: python3 ci/docker_hub.py
