name: dagger
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  dagger:
    name: dagger
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        env: 
          TEST_VAR: 'test'
        run: echo "My API_KEY is ${{secrets.DOCKER_HUB_PASSWORD}} . name is ${{ env.TEST_VAR }} test var $TEST_VAR"
    
      # - uses: actions/checkout@v3
      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.10"
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install dagger-io
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Install dagger
      #   run: pip install dagger-io
      # - shell: bash
      #   env:
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #   run: |
      #     echo "pw $DOCKER_HUB_PASSWORD"
      # - name: Run dagger
      #   run: python3 ci/docker_hub.py $DOCKER_HUB_PASSWORD
