name: dagger
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  dagger:
    name: dagger
    runs-on: ubuntu-latest
    env: 
      TEST_VAR: 'test'
      LAST: ${{ vars.PEXI }}
      DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Print name
        run: | 
          echo My API_KEY is ${{ env.PIPPELI }} . PEKKA_VAR is ${{ env.PEKKA_VAR }} - TEST_VAR $TEST_VAR - LAST ${{ env.LAST }} - kakka is $KAKKA
          echo PW is $OLLON
          echo NEKKE is $NEKKE
          echo KAKKA is $KAKKA
        env:
          KAKKA: ${{ vars.PEXI }}
          OLLON: ${{ secrets.PIPPELI_SECRET }}
          NEKKE: ${{ vars.PEXI }}
    
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagger-io
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install dagger
        run: pip install dagger-io
        env: 
          PIPPELI: 'pipeli'
      - name: Run dagger
        run: python3 ci/docker_hub.py ${{ env.DOCKER_HUB_PW }}
